/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "STM32F103C6xx.h"
#include "STM32F103C6x_GPIO.h"

void RCC_Init()
{
	MCAL_RCC_ENABLE_GPIOA();
	MCAL_RCC_ENABLE_GPIOB();
}
void GPIO_Init()
{
	s_GPIO_PIN_CONFIG_t* PIN_CFG;
	PIN_CFG->PIN_NUM=GPIO_PIN1;
	PIN_CFG->PIN_MODE = MCAL_GPIO_GPO_PP;
	PIN_CFG->PIN_OUTPUT_SPEED = MCAL_GPIO_OUT_10MHZ;
	MCAL_vid_GPIO_INIT(GPIOB, PIN_CFG);


	PIN_CFG->PIN_NUM=GPIO_PIN13;
	PIN_CFG->PIN_MODE = MCAL_GPIO_GPO_PP;
	PIN_CFG->PIN_OUTPUT_SPEED = MCAL_GPIO_OUT_10MHZ;
	MCAL_vid_GPIO_INIT(GPIOB, PIN_CFG);

	PIN_CFG->PIN_NUM=GPIO_PIN1;
	PIN_CFG->PIN_MODE = MCAL_GPIO_FLO_IN;
	PIN_CFG->PIN_OUTPUT_SPEED = MCAL_GPIO_INPUT;
	MCAL_vid_GPIO_INIT(GPIOA, PIN_CFG);

	PIN_CFG->PIN_NUM=GPIO_PIN13;
	PIN_CFG->PIN_MODE = MCAL_GPIO_FLO_IN;
	PIN_CFG->PIN_OUTPUT_SPEED = MCAL_GPIO_INPUT;
	MCAL_vid_GPIO_INIT(GPIOA, PIN_CFG);
}

int main(void)
{
	volatile uint8_t i;
	RCC_Init();
	GPIO_Init();
	while(1)
	{
		if(MCAL_uint8_GPIO_READ_PIN(GPIOA, GPIO_PIN1) == (uint8_t)0)
		{
			MCAL_vid_TOGGLE_PIN(GPIOB, GPIO_PIN1);
			while( MCAL_uint8_GPIO_READ_PIN(GPIOA, GPIO_PIN1) == (uint8_t)0 );
		}
		if( MCAL_uint8_GPIO_READ_PIN(GPIOA, GPIO_PIN13) == (uint8_t)1 )
		{
			MCAL_vid_TOGGLE_PIN(GPIOB, GPIO_PIN13);
		}
		for(i=0;i<255;i++)
			;
	}
	return 0;
}
