/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * Lab requirements:::::::
 * 1-GPIO Port_B Pin_1 to be configured OUTPUT Pull UP and connected to a led, resistor, 3.3V.
 * 2-GPIO Port_B Pin_13 to be configured OUTPUT Pull UP and connected to a led, resistor, 3.3V.
 * 3-GPIO Port_A Pin_1 to be configured INPUT Floating and connected to a switch,Pull up circuit.
 * 3-GPIO Port_A Pin_13 to be configured INPUT Floating and connected to a switch,Pull down circuit.
 * */

#include "stdint.h"


#define GPIO_PA_BASE 0x40010800
#define GPIOA_CRL *(volatile uint32_t*)(GPIO_PA_BASE + 0x00)
#define GPIOA_CRH *(volatile uint32_t*)(GPIO_PA_BASE + 0x04)
#define GPIOA_IDR *(volatile uint32_t*)(GPIO_PA_BASE + 0x08)
#define GPIOA_ODR *(volatile uint32_t*)(GPIO_PA_BASE + 0x0C)


#define GPIO_PB_BASE 0x40010C00
#define GPIOB_CRL *(volatile uint32_t*)(GPIO_PB_BASE + 0x00)
#define GPIOB_CRH *(volatile uint32_t*)(GPIO_PB_BASE + 0x04)
#define GPIOB_IDR *(volatile uint32_t*)(GPIO_PB_BASE + 0x08)
#define GPIOB_ODR *(volatile uint32_t*)(GPIO_PB_BASE + 0x0C)

#define RCC_BASE 0x40021000

#define RCC_APB2_ENR *(volatile uint32_t*)(RCC_BASE + 0x18)
#define RCC_IOP_A	2
#define RCC_IOP_B	3
void RCC_Init()
{
	RCC_APB2_ENR |= (0b11)<<2;/*Enable clock for GPIO port A and B together*/
}
void GPIO_Init()
{
	GPIOA_CRL =0;
	GPIOA_CRH =0;
	GPIOB_CRL =0;
	GPIOB_CRH =0;
	GPIOA_ODR =0;
	GPIOB_ODR =0;
	/*input pins configuration*/
	GPIOA_CRL |= (0b0100)<<4;
	GPIOA_CRH |= (0b0100)<<20;

	/*Output pins configuration*/
	GPIOB_CRL |= (0b0001)<<4;
	GPIOB_CRH |= (0b0001)<<20;

}

int main(void)
{
	volatile uint8_t i;
	RCC_Init();
	GPIO_Init();
	while(1)
	{
		if( ((GPIOA_IDR &= (1<<1)) >>1) == 0 )
		{
			GPIOB_ODR ^= 1 << 1;
			while( ((GPIOA_IDR &= (1<<1)) >>1) == 0 );
		}
		if( ((GPIOA_IDR &= (1<<13)) >>13) == 1 )
		{
			GPIOB_ODR ^= 1 << 13;
		}
		for(i=0;i<255;i++)
			;

	}
	return 0;
}
