/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdio.h>
#include"Platform_Types.h"

#define RCC_BASE 		0x40021000
#define PORT_A_BASE		0x40010800

#define RCC_APB2ENR		*(v_uint32_t*)(RCC_BASE 	+ 0x18)		/* Bit 2 should be set to enable clock for GPIO peripheral*/
#define GPIO_CRH		*(v_uint32_t*)(PORT_A_BASE 	+ 0x04)		/* Control register which we need to set our port OUTPUT*/
#define GPIO_ODR		*(v_uint32_t*)(PORT_A_BASE 	+ 0x0C)		/* OUTPUT DATA REGISTER to be toggled in pin 13	*/


int main(void)
{
	volatile int i;
	RCC_APB2ENR |= 1<<2;		/*Enable clock for GPIO*/
	GPIO_CRH &= 0xFF0FFFFF;		/*	Make control for PortA out*/
	GPIO_CRH |= 0x00200000;
    /* Loop forever */
	while(1)
	{
		GPIO_ODR |= 1<<13;
		for(i=0;i<5000;i++);
		GPIO_ODR &= ~(1<<13);
		for(i=0;i<5000;i++);
	}

}
