#include "STM32F103C6xx.h"
#include "GPIO.h"
#include "EXTI.h"
#include "RCC.h"
#include "UART.h"
#include "stdlib.h"
void RCC_Init()
{
	MCAL_RCC_ENABLE_GPIOA();
	MCAL_RCC_ENABLE_GPIOB();

}
//void GPIO_Init()
//{
//	s_GPIO_PIN_CONFIG_t* PIN_CFG;
//	PIN_CFG->PIN_NUM=GPIO_PIN1;
//	PIN_CFG->PIN_MODE = MCAL_GPIO_GPO_PP;
//	PIN_CFG->PIN_OUTPUT_SPEED = MCAL_GPIO_OUT_10MHZ;
//	MCAL_vid_GPIO_INIT(GPIOB, PIN_CFG);
//
//	PIN_CFG->PIN_NUM=GPIO_PIN13;
//	PIN_CFG->PIN_MODE = MCAL_GPIO_GPO_PP;
//	PIN_CFG->PIN_OUTPUT_SPEED = MCAL_GPIO_OUT_10MHZ;
//	MCAL_vid_GPIO_INIT(GPIOB, PIN_CFG);
//
//	PIN_CFG->PIN_NUM=GPIO_PIN1;
//	PIN_CFG->PIN_MODE = MCAL_GPIO_FLO_IN;
//	PIN_CFG->PIN_OUTPUT_SPEED = MCAL_GPIO_INPUT;
//	MCAL_vid_GPIO_INIT(GPIOA, PIN_CFG);
//
//	PIN_CFG->PIN_NUM=GPIO_PIN13;
//	PIN_CFG->PIN_MODE = MCAL_GPIO_FLO_IN;
//	PIN_CFG->PIN_OUTPUT_SPEED = MCAL_GPIO_INPUT;
//	MCAL_vid_GPIO_INIT(GPIOA, PIN_CFG);
//}


uint8_t payload;

int main(void)
{
	RCC_Init();

	s_USART_Config_t USART_CFG;
	USART_CFG.BAUD_RATE=USART_BR_115200;
	USART_CFG.FLOW_CTRL=USART_FLOW_CTRL_NONE;
	USART_CFG.IRQ_ENABLE=USART_IRQ_ENABLE_NONE;
	USART_CFG.PARITY=USART_PARITY_OFF;
	USART_CFG.PAYLOAD = USART_PAYLOAD_8BITS;
	USART_CFG.STOP_BITS=USART_STOP_BITS1;
	USART_CFG.USART_MODE= USART_MODE_Rx_Tx_ON;
	USART_CFG.P_IRQ_CALLBACK = NULL;
	MCAL_UART_INIT(USART1, &USART_CFG);
	MCAL_UART_GPIO_SET_PINS(USART1);
	while(1)
	{
		MCAL_UART_RCV_DATA(USART1, &payload, Enable);
		MCAL_UART_SND_DATA(USART1, &payload, Enable);
	}
	return 0;
}
